language: java
jdk: openjdk8
script:
  - mvn verify
after_success:
  - mvn test jacoco:report coveralls:report
before_deploy:
  - mvn clean package
  - mvn assembly:single
  - yes | gem update --system --force
  - gem install bundler
  - gem install uri
  - gem install logger
deploy:
  provider: releases
  api_key:
    secure: wFmzYdB32pFJ1uo20uDk1pWXdl/oPo267WlZmcSlsy4TozXclN6qaSTbkigYbWRsyiNQTv51DjcszgOpdnDAUcNWuEQHmvS1nZ8T/2rPXsWfPumB+Ty3LjLLYfUEJDWKNLqu6YWWpIDeFgvEhbVnPywhNNeIOmlmL9qvxn40KbEADwWe8qtI67TLM6xKXYOX4Okt5v9s8YUnWj0lOiaguoF/3zoOOQG0+9DkhSOuNHawc9Da9CYj9tMEFLNPL+RhiVyfcV+TphXe6UJIMw3hOCd1wVsLy3A+/JU9Oyagzim0pAa8VUQpM3FPtQLuwrs22X47G+hfZxpjT592byznZrdlInXibsu2yx4IdkO7dTSNQwQu3EgSwd8jP/dG/WZ3MZ2px6sdNJcH9hE8MJ4/95s6OOHER9XLvLWw2E6/+vKJ/dakrUu/SQc9Fdmm5B8ivBKj9CWoJYSIqIZnQUZ7jQM0tMzR4VH5laoyZiOt3dcy1JKCxYXEjwjNXZIwc1CQS82pRQeSrKuV0v1py7AoBuVAsVBbhvt/BktQtpGGaEqId92nv+3185XbX7ASJ7bZjDAKQ7uo+q6tlq/x7WkKHV93YAWigCJuNS2Upd+KoB5Aajgqp/x0g6Mu+Nz0S9147LqGrjpS9Sxp7LuI+hDN6bO0C3Qj1nkPWBeT10xPdvo=
  file: target/dataloader.zip
  skip_cleanup: true
  on:
    repo: bullhorn/dataloader
    branch: master
    tags: true
