language: java

jdk: openjdk8

cache:
  directories:
    - node_modules

before_install:
  - nvm install 12

install:
  - npm install

script:
  - mvn verify

after_success:
  - mvn test jacoco:report coveralls:report

before_deploy:
  - mvn clean package
  - mvn assembly:single

deploy:
  provider: releases
  api_key:
    secure: x3EMIpn9nZ20wcuyiwekl+ALgSEwIaMeJjlkWqFe7Wq0WknjfA8lwVDE+D7FYWtl0xU5a1wmYuAULQtKGusDYEDl7lULUXdKuhvHzsLalHoyj98Uo2ccNjjglZVBW72ujtnWF2MOEEkH6cFspi00lfan9xWJpRBZhdvXbl9dI3wrw5N9EfU+KuHeo/5TPULtyYDHLch+RnCo2/Kz2pBaqukafXgnPCxGQLoZ9tt+dlOUJnJL03lXnat61N8lG+4yCFI+x6e8HYlj1yGtVbEc6zPaomOuGAngDC+w2PfU43jWKN5cIDwDoKP+4f2IAGar435jaIXtQqG8xcd/oVXoAe7jvKXlCu2auRFf+hePj522+4GokLF4/P/zQX+fiy4nkvO7OzzlAnqITbKlJz53HMdIbpfk61eSgycUXkDRMoU9bM91QqlJRizqi39wJlAUGKg/QEpXweJzE1ZIvUNSlYOPC9pMMtLTaRmYTZ7cLHvikWdADyQ7wTjRd2rOL58LtnMn2UiFl7lkuESX25BY2hIWvIDkuJqcs4xKcyx9WIqmtgZjsf2o3OhgIBflMw1JFZQHUUIXC4h5v3GNd4xTQRJp2qNFzS11YjYI1cxbtsUcTrO3SIf5XlwnPH6gd7hnasqOy3A1NHvw8dmEUseCo0rr0AZdXCRMkh47qp7DyBU=
  file: target/dataloader.zip
  skip_cleanup: true
  on:
    repo: bullhorn/dataloader
    branch: master
    tags: true
